[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.26",
    "langgraph>=0.5.2",
    "openai>=1.93.3",
]
